version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: plantcare_backend_jenkins
    ports:
      - "3200:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://rumerjaved7:nZlh8VxWpiANvjh5@cluster0.dqasiyv.mongodb.net/ShopSphere?retryWrites=true
    volumes:
      - ./server:/app
    network_mode: "host"  # ✅ Added this line to fix npm internet issue temporarily

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: plantcare_frontend_jenkins
    ports:
      - "5200:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - server
    volumes:
      - ./my-project:/app
    networks:
      - plantcare-ci-network

networks:
  plantcare-ci-network:
    driver: bridge
