version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plant-backend
    ports:
      - "5000:5000"
    working_dir: /app
    command: node server.js
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plant-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    network_mode: host
